---
title: "RWorkSheet_Barrientos#3a"
author: "Barrientos, Milfrance D"
date: "2024-10-01"
output:
  pdf_document: default
  html_document:
    df_print: paged
---

```{r}
#Using Vectors 
# 1. There is a built-in vector LETTERS contains the uppercase letters of the alphabet and letters                          which contains the lowercase letters of the alphabet.
LETTERS <- c("A", "B", "C", "D", "E", "F", "G", "H", "I",
             "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z")
# a. You need to produce a vector that contains the first 11 letters.

LETTERS[1:11]

# b. Produce a vector that contains the odd numbered letters.
LETTERS[seq(1,26,2)]

# c. Produce a vector that contains the vowels
LETTERS[c(1,5,9,15,21)]
```

```{r}
# Based on the above vector letters: 
letters <- c("a", "b", "c", "d", "e", "f", "g", "h", "i",
             "j", "k", "l", "m", "n", "o", "p", "q", "r", "s", "t", "u", "v", "w", "x", "y", "z")

# d. Produce a vector that contains the last 5 lowercase letters.
letters[22:26]

# e. Produce a vector that contains letters between 15 to 24 letters in lowercase.
letters[15:24]
```

```{r}
# Create a vector(not a dataframe) with the average temperatures in April for                                            Tugue-garao City, Manila, Iloilo City, Tacloban, Samal Island, and Davao City. 
# The average temperatures in Celcius are 42, 39, 34, 34, 30, and 27 degrees. 

# a.  What is the R code and its result for creating a character vector for the city/town of Tuguegarao City, Manila, Iloilo City, Tacloban,Samal Island, and Davao City?
# Name the object as city. The names should follow the same order as in the instruction.
city <- c("Tuguegarao City", "Manila", "Iloilo City", "Tacloban", "Samal Island", "Davao City")

```
```{r}

# b. The average temperatures in Celcius are 42, 39, 34, 34, 30, and 27 degrees.Name the object as temp.
# Write the R code and its output. Numbers should also follow what is in the instruction.
temp <- c (42, 39 ,34, 34, 30, 27)
city <- c("Tuguegarao City", "Manila", "Iloilo City", "Tacloban", "Samal Island", "Davao City")

#c. Create a dataframe to combine the city and the temp by using ‘data.frame(). What the R code and its result?
df <- data.frame(city, temp)

# d. Associate the dataframe you have created in 2.(c) by naming the columns using the names() function. 
# Change the column names by using names() function as City and Temperature. 
# What is the R code and its result?
names(df) <- c("city", "temp")

# e. Print the structure by using str() function. Describe the output.
str(df)
# the output is a data frame with 6 observations of 2 variables
```
```{r}
# f. From the answer in d, what is the content of row 3       and row 4 What is its R code and its output?
df[3:4,]

# g. From the answer in d, display the city with highest temperature and the city with the lowest temperature.        What is its R code and its output? 
df[which.max(df$temp),]
df[which.min(df$temp),]

```
```{r}
# 2. Create a matrix of one to eight and eleven to fourteen with four columns and three rows.
matrix1 <- matrix(c(1:8, 11:14), nrow = 3, ncol = 4)
# a. What will be the R code for the #2 question and its result?
matrix1

# b. Multiply the matrix by two. What is its R code and its result?
matrix1 * 2

# c. What is the content of row 2? What is its R code?
# the content of row 2 is 3 5 7 9 and its R code is matrix1 * 2

# d. What will be the R code if you want to display the column 3 and column 4 in row 1 and row 2? What is its output?
matrix1[1:2, 3:4]

# e. What is the R code is you want to display only the columns in 2 and 3, row 3? What is its output?
matrix1[3, 2:3]

# f. What is the R code is you want to display only the columns 4? What is its output?
matrix1[, 4]

# g. Name the rows as isa, dalawa, tatlo and columns as uno, dos, tres, quatro for the matrix that was created in b.‘.     What is its R code and corresponding output?
rownames(matrix1) <- c("isa", "dalawa", "tatlo")
colnames(matrix1) <- c("uno", "dos", "tres", "quatro")
matrix1

# h. From the original matrix you have created in a, reshape the matrix by assigning a new dimension with dim().
# New dimensions should have 2 columns and 6 rows. What will be the R code and its output?
dim(matrix1) <- c(6, 2)
matrix1
```

```{r}
# ARRAY
# 3. An array contains 1, 2, 3, 6, 7, 8, 9, 0, 3, 4, 5, 1
array <- c(1,2,3,6,7,8,9,0,3,4,5,1)
array 

# a.Create an array for the above numeric values. Each values will be repeated twice 
# What will be the R code if you are to create a three-dimensional array with 4 columns and 2 rows. What will be its output?
array2 <- rep(array, time =2)
array2
array3d <- array(array2, dim = c (2,4,3))
array3d

# b. How many dimensions do your array have?
# It has 3 arrays

#c. Name the rows as lowercase letters and columns as uppercase letters starting from the A.                                   The array names should be “1st-Dimensional Array”, “2nd-Dimensional Array”, and “3rd-Dimensional Array”.        What will be the R codes and its output?
rownames <- c("a", "b")
colnames <- c ("A", "B", "C", "D")
dimnames <- list(rownames,colnames , c ("1st-Dimensional Array", "2nd-Dimensional Array", "3rd-Dimensional Array"))
dimnames(array3d) <- dimnames
array3d
```


