---
title: "RWorkSheets_Barrientos#1"
author: "BARRIENTOS,MILFRANCE D."
date: "2024-09-04"
output:
  pdf_document: default
  html_document: default
---
1.
```{r} 
age <- c(34, 28, 22, 36, 27, 18, 52, 39, 42, 29,
35, 31, 27, 22, 37, 34, 19, 20, 57, 49, 50, 37, 46, 25, 17, 37, 42, 53, 41, 51, 35, 24, 33, 41.)
length (age)

age <- c(34, 28, 22, 36, 27, 18, 52, 39, 42, 29,
35, 31, 27, 22, 37, 34, 19, 20, 57, 49, 50, 37, 46, 25, 17, 37, 42, 53, 41, 51, 35, 24, 33, 41.)


```
2.
```{r}
reciprocal <- 1 / age
print (reciprocal)

```
3.

```{r}
new_age <- c(age,0,age)
print (new_age)

```
## What Happen to the new_age? 
  - In new_age, you will see the original age values, followed by a 0, and then the same age values again.

4
```{r}
sort(age)
sort (age)
```
5
```{r}
min (age) 
print (age)
```
```{r}
max (age)

```
6
```{r}
data <- c(2.4, 2.8, 2.1, 2.5, 2.4, 2.2, 2.5,
          2.3, 2.5, 2.3, 2.4, 2.7)
print(data)


length(data)
```

```{r}
data <- c(2.4, 2.8, 2.1, 2.5, 2.4, 2.2, 2.5,
          2.3, 2.5, 2.3, 2.4, 2.7)
data <- data * 2
print (data)
```

 
 8.1
```{r}
sequence <- seq (1,100)
print (sequence)

```
8.2
```{r}
sequence <- seq (20, 60)

print (sequence)
```
8.3 
```{r}
sequence <- seq (20, 60)
mean_value <- mean(sequence)
mean_value 

```
8.4
```{r}
sequence <- seq(51, 91)
sum_value <- sum(sequence)
sum_value
```
8.5
```{r}
# 8.1 
integers_1_to_100 <- 1:100
print(integers_1_to_100)

# 8.2 
numbers_20_to_60 <- 20:60
print(numbers_20_to_60)

# 8.3 
mean_20_to_60 <- mean(numbers_20_to_60)
print(mean_20_to_60)

# 8.4 
numbers_51_to_91 <- 51:91
sum_51_to_91 <- sum(numbers_51_to_91)
print(sum_51_to_91)


```


```{r}
```


```{r}

# B. 8.1 Generates data from 1 - 100
data <- 1:1000
length(data)  

# 8.2 Filter even numbers
even_data <- data[data %% 2 == 0]
length(even_data)  

# 8.3 Filter numbers greater than 500
greater_than_500 <- data[data > 500]
length(greater_than_500)  

# 8.4 Sum of numbers less than 100
sum_less_than_100 <- sum(data[data < 100])
sum_less_than_100

# C. 
# 8.1 
data_8_1 <- 1:100
length(data_8_1)  # Number of data points

# 8.2 
data_8_2 <- 20:60
length(data_8_2)  # Number of data points

# 
mean_8_3 <- mean(data_8_2)
mean_8_3

# 8.4 
data_8_4 <- 51:91
sum_8_4 <- sum(data_8_4)
sum_8_4


```


9.
```{r}
filter <- Filter(function(i) { all(i %% c(3, 5, 7) != 0) }, seq(1, 100))
print(filter)

```
10. 
```{r}
sequence_backwards <- rev (seq(1,100))
print (sequence_backwards)
```
11. 
```{r}
multiples <- Filter(function(i) { i %% 3 == 0 || i %% 5 == 0 }, seq(1, 24))
sum_multiples <- sum(multiples)

multiples
sum_multiples
```
12. 
## The statement will not immediately print it because the expression is incomplete.

13.
```{r}
score <- c(72, 86, 92, 63, 88, 89, 91, 92, 75, 75, 77)
x2 <- score[2]
x3 <- score[3]
print(x2)
print(x3)
```
14. 
```{r}
# A
a <- c(1, 2, NA, 4, NA, 6, 7)

print(a, na.print="-999")
# B

# The -999 is not actually changing the vector a it's just a way to represent NA values during the print operation.

``` 
15. 
```{r}
name = readline(prompt="Input your name: ")
age = readline(prompt="Input your age: ")
print(paste("My name is", name, "and I am", age, "years old."))
print(R.version.string)
```












 
 









