---
title: "RWorkSheet_Barrientos#3b"
author: "Barrientos, Milfrance D"
date: "2024-10-02"
output:
  pdf_document: default
  html_document:
    df_print: paged
---

```{r}
# 1. Create a data frame using the table below.

#a. Write the codes.
respondents_data <- data.frame (
respondents = 1:20,
sex = c(2, 2, 1, 2, 2, 2, 2, 2, 2, 1, 1, 2, 1, 2, 2, 1, 2, 1,1, 2),
fathers_occupation = c(1, 3, 3, 3, 1, 2, 3, 1, 1, 1, 3, 2, 1, 3,3, 1, 3, 1, 2, 1), 
person_at_home = c(5, 7, 3, 8, 5, 9, 6, 7, 8, 4, 7, 5, 4, 7, 8, 8, 3, 11, 7, 6),siblings_at_school = c(6, 4, 4, 1, 2, 1, 5, 3, 1, 2, 3, 2, 5, 5, 2, 1, 2, 5, 3, 2), typeOfHouses = c(1, 2, 3, 1, 1, 3, 3, 1, 2, 3, 2, 3, 2, 2, 3, 3, 3, 3, 3, 2)
)
respondents_data
                   

#b. Describe the data. Get the structure or the summary of the data
str(respondents_data)
respondents_data

# c.Is the mean number of siblings attending is 5?
mean(respondents_data$siblings_at_school)
# no it is 2.95

# d. Extract the 1st two rows and then all the columns using the subsetting functions. 
# Write the codes and its output.
firsttworows <- respondents_data [1:2, ]
firsttworows


# e. Extract 3rd and 5th row with 2nd and 4th column. Write the codes and its result.
subset <- respondents_data[c(3, 5), c(2, 4)]
subset

# f. Select the variable types of houses then store the vector that results as types_houses. Write the codes.
type_houses <- respondents_data$typeOfHouses
type_houses

# g. Select only all Males respondent that their father occupation was farmer. Write the codes and its output.
maleFarmers <- respondents_data[respondents_data$sex == 1 & respondents_data$fathers_occupation == 1, ]
maleFarmers

# h. Select only all females respondent that have greater than or equal to 5 number of siblings attending school. 
# Write the codes and its outputs.
fem <- respondents_data[respondents_data$sex == 2 & respondents_data$siblings_at_school >=5, ]
fem
```
```{r}
#2. Write a R program to create an empty data frame. Using the following codes:
df = data.frame(Ints=integer(),

Doubles=double(), Characters=character(),
Logicals=logical(),
Factors=factor(),
stringsAsFactors=FALSE)

print("Structure of the empty dataframe:")
print(str(df))

# a. describe the results - the result is an empty data frame with 0 observations of 5 variables

```
```{r}
# 3.Create a .csv file of this. Save it as HouseholdData.csv
# a. Import the csv file into the R environment. Write the codes.
library(readxl)
Household <- read_excel("C:/PROJ/HouseholdData.xlsx")
Household

#b. Convert the Sex into factor using factor() function and change it into integer.
# [Legend: Male = 1 and Female = 2]. Write the R codes and its output.
Household$Sex <- factor(Household$Sex)
Household$Sex <- as.integer(Household$Sex)
Household

# c. Convert the Type of Houses into factor and change it into integer. [Legend: Wood = 1; Congrete = 2; Semi-Congrete = 3].  # Write the R codes and its output.
Household$Types_of_Houses <- factor(Household$Types_of_Houses, levels = c("Wood", "Congrete", "Semi-congrete"), labels = c(1, 2, 3))
Household$Types_of_Houses <- as.integer(as.character(Household$Types_of_Houses))
Household


# d. On father’s occupation, factor it as Farmer = 1; Driver = 2; and Others = 3. What is the R code and its output?
Household$Fathers_Occupation <- factor(Household$Fathers_Occupation, levels = c("Farmer", "Driver", "Others"), labels = c(1, 2, 3))
Household$Fathers_Occupation <- as.integer(as.character(Household$Fathers_Occupation))

#e. Select only all females respondent that has a father whose occupation is driver. 
# Write the codes and its output.
fem <- Household[Household$Sex == 2 & Household$Fathers_Occupation == 2, ]
fem

# f. Select the respondents that have greater than or equal to 5 number of siblings attending school. 
# Write the codes and its output.
sib <- Household[Household$Siblings_at_School >= 5, ]
sib
```
```{r}
# 4. interpret the graph 
# The graph shows the sentiment of tweets collected on different days. 
# The sentiment is classified into three categories: 
# the positive represented by Blue, the negative represented by Red, 
# and the neutral represented by Yellow. 
# The data is shown from July 14, 2020, to July 20, 2020. 
# The Y-axis represents the count of tweets, while the X-axis 
# shows the different sentiment categories for each day. 
# On almost every day, the Red or Negative sentiment is the highest, 
# followed by the Blue or Positive sentiment, and the Yellow 
# or Neutral sentiment is the lowest. 
# The highest count of tweets is on July 15, 2020, 
# while the lowest count of tweets is on July 20, 2020. 
# The sentiment of the tweets is mostly negative, followed by positive, 
# and the least is neutral.


```


