---
title: "RWorkSheet_Barrientos#2"
author: "Barrientos, Milfrance D"
date: "2024-09-25"
output: html_document
---

# 1.Using Vectors
```{r}
#a. Sequence from -5 to 5. Write the R code and its output.
seq(-5,5)
# Describe its output.
# - The output is a sequence of numbers from -5 to 5.
# b. x <- 1:7. What will be the value of x?
x <- 1:7
x

```
# 2.
```{r}
# Create a vector using seq() function
# a. seq(1, 3, by=0.2) # specify step size
seq(1, 3, by=0.2)
# Write the R script and its output. Describe the output.
# - The output is a sequence of numbers from 1 to 3 with a step size of 0.2.
```
#3. 
```{r}
#A factory has a census of its workers. There are 50 workers in total. The following list shows their ages: 34, 28, 22, 36, 27, 18, 52, 39, 42, 29, 35, 31, 27,22, 37, 34, 19, 20, 57, 49, 50, 37, 46, 25, 17, 37, 43, 53, 41, 51, 35,24,33, 41, 53, 40, 18, 44, 38, 41, 48, 27, 39, 19, 30, 61, 54, 58, 26,18.
# a. Access 3rd element, what is the value?
ages <- c(34, 28, 22, 36, 27, 18, 52, 39, 42, 29, 35, 31, 27,22, 37, 34, 19, 20, 57, 49, 50, 37, 46, 25, 17, 37, 43, 53, 41, 51, 35,24,33, 41, 53, 40, 18, 44, 38, 41, 48, 27, 39, 19, 30, 61, 54, 58, 26,18)

ages[3]
#b. Access 2nd and 4th element, what are the values?
ages [c(2,4)]

#c. Access all but the 4th and 12th element is not included. Write the R script and its output.
ages[c(-4,-12)]

```
4. 
```{r}
#4. *Create a vector x <- c("first"=3, "second"=0, "third"=9) Then named the vector, names(x).
x <- c("first"=3, "second"=0, "third"=9)
#a. Print the results. Then access x[c("first", "third")]. # Describe the output.
names (x)
# the output will be the numbers that I assigned to the names of the vector.

#b. Write the code and its output.
x[c("first", "third")]

# The output shows "first" with a value of 3 and "third" with a value of 9.

```
5.
```{r}
#Create a sequence x from -3:2.
seq(-3:2)

#a. Modify 2nd element and change it to 0;
x[2] <- 0
x
#Describe the output.

```
6.
```{r}
# 6. *The following data shows the diesel fuel purchased by Mr. Cruz.

#Month Jan Feb March Apr May June Price per liter (PhP) 52.50 57.25 60.00 65.00 74.25 54.00 Purchase–quantity(Liters) 25 30 40 50 10 45
# a. Create a data frame for month, price per liter (php)and purchase-quantity (liter). Write the R scripts andits output.

diesel_data <- data.frame(
  Month = c("Jan", "Feb", "March", "Apr", "May", "June"),
  Price_per_Liter = c(52.50, 57.25, 60.00, 65.00, 74.25, 54.00),
  Purchase_Quantity = c(25, 30, 40, 50, 10, 45)
)
print(diesel_data)

# b. What is the average fuel expenditure of Mr. Cruz fromJan to June? Note: Use ‘weighted.mean(liter,purchase)‘. Write the R scripts and its output.
weighted.mean(diesel_data$Price_per_Liter,diesel_data$Purchase_Quantity)

```
7.
```{r}
#R has actually lots of built-in datasets. For example, the rivers data “gives the lengths (in miles) of 141 “major” rivers in North America, as compiled by the US Geological Survey”.     

#a. Type “rivers” in your R console.Create a vector data with 7 elements, containing the number of elements (length) in rivers, their sum (sum), mean (mean), median(median), variance(var), standard deviation(sd),minimum (min) and maximum (max).
data <- c(
  length(rivers),
  sum(rivers),
  mean(rivers),
  median(rivers),
  var(rivers),
  sd(rivers),
  min(rivers),
  max(rivers)
)
print(data)

#b. What are the results?
# - The results are the length, sum, mean, median, variance, standard deviation, minimum, and maximum of the rivers data.


#c. Write the R scripts and its outputs.
# - 

```
8.
```{r}
# The table below gives the 25 most powerful celebrities and their annual pay as ranked by the editions of Forbes magazine and as listed on the Forbes.com website.
#a. Create vectors according to the above table. Write the R scripts and its output.
power_ranking <- c(1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25)

celebrity_name <- c("Tom Cruise", "Rolling Stones", "Ophrah Winfrey", "U2", "Tiger Woods", "Steven Spielberg", "Howard Stern", "50 Cent", "Cast of Desperate Housewives", "Dan Brown", "Bruuce Springsteen", "Donald Trump", "Muhammad Ali","Paul McCartney", "George Lucas", "Elthon John", "David Letterman", "Phil Mickelson", "J.K Rowling", "Brad Pitt", "Peter Jackson", "Dr. Phil McGraw", "Jay Leno", "Celine Dion", "Koby Bryant")

pay <- c(67,90, 225, 110, 87, 332, 302, 41, 52, 88, 55, 44, 55, 40, 233, 34, 40, 47, 75, 25, 39, 45, 32, 40, 31)
print(power_ranking)
print(celebrity_name)
print(pay)

#b. Modify the power ranking and pay of J.K. Rowling. Change power ranking to 15 and pay to 90. Write the R scripts and its output.
power_ranking[19] <- 15
pay [19] <- 90

# c. Create an excel file from the table above and save it as csv file(PowerRanking). Import the csv file into the RStudio. What is the R script?
write.csv(data.frame(power_ranking, celebrity_name, pay), "PowerRanking.csv")
power_ranking_data <- read.csv("PowerRanking.csv")
print(power_ranking_data)

#d. Access the rows 10 to 20 and save it as Ranks.RData.    Write the R script and its output. 
selected_ranks <- power_ranking_data[10:20, ]
save(selected_ranks, file = "Ranks.RData")  
print(selected_ranks)  

#e. Describe its output.
# - The output is the data of the 10th to 20th row of the data frame.
```

9.
```{r}
#a. Import the excel file into your RStudio. What is the R script?
library(readxl)
hotel_v <- read_excel("C:/PROJ/hotels-vienna.xlsx")
print(hotel_v)
#b.How many dimensions does the dataset have? What is the R script? What is its output?

dim(hotel_v)
# - The dataset has 3 dimensions.

#c. Select columns country, neighbourhood, price, stars, accomodation_type, and ratings. Write the R script.


#d. Save the data as **new.RData to your RStudio. Write the     R script. 
save(hotel_v, file = "new.RData")

#e.Display the first six rows and last six rows of the new RData. What is the R script?
head(hotel_v)

```
10. 
```{r}
 #Create a list of ten (10) vegetables you ate during your lifetime. If none, just list down.
#a. Write the R scripts and its output.
vegetables <- c("carrots", "cabbage", "broccoli", "spinach", "lettuce", "tomato", "bell pepper", "onion", "garlic", "potato")

#b. Add 2 additional vegetables after the last vegetables in the list. What is the R script and its output?
append (vegetables, c("eggplant", "cucumber"))
#c. Add 4 additional vegetables after index 5. How many datapoints does your vegetable list have? What is the R script and its output?
append(vegetables, c("eggplant", "cucumber", "zucchini", "asparagus"), after = 5)
length(vegetables)
# - The vegetable list has 10 data points.
#d.Remove the vegetables in index 5, 10, and 15. How many vegetables were left? Write the codes and its output.
vegetables <- vegetables[-c(5, 10, 15)]
length(vegetables)
# - There are 7 vegetables left.
```